/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.Helpers;
import static Interfaces.Inicio.buscaMinaApp;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *Configura el tamaño nxn de el tablero 
 * @author Miguel
 * 
 */
public class ConfigTamaño extends javax.swing.JFrame {
    
    
    
   

    /**
 * Constructor de la clase ConfigTamaño.
 * Inicializa la interfaz gráfica de configuración de tamaño del tablero,
 * estableciendo su visibilidad, deshabilitando la opción de redimensionado
 * y centrando la ventana en la pantalla.
 */
    public ConfigTamaño() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        valorN = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        continuar = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorN.setModel(new javax.swing.SpinnerNumberModel(3, 3, 10, 1));
        jPanel1.add(valorN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 220, 30));

        jLabel1.setText("El tablero es nxn. Indica el valor de n:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        continuar.setText("Continuar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });
        jPanel1.add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 220, -1));

        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 60, 50));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setText("Tamaño del Tablero");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Boton para salir de el programa 
 * @param evt 
 */
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed
/**
 * Boton que genera el tablero y te lleva de una vez a este mismo para comenzar el juego
 * @param evt 
 */
    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        // TODO add your handling code here:
        int valorInt = (int) valorN.getValue();
        buscaMinaApp.generarGrafoTablero(valorInt);
        buscaMinaApp.setN(valorInt);
        // Solicitar al usuario la cantidad de minas
        Helpers helper = new Helpers();
        String inputMinas = JOptionPane.showInputDialog("Ingrese la cantidad de minas (1 - " + (valorInt * valorInt) + "):");

        if (inputMinas == null) {
            JOptionPane.showMessageDialog(null, "Operación cancelada. No se generará el tablero.");
            return; // Sale de la función si el usuario cancela
        }

        int cantidadMinas = helper.convertirNumero(inputMinas);

// Validar el número ingresado
        while (cantidadMinas < 1 || cantidadMinas > (valorInt * valorInt)) {
            JOptionPane.showMessageDialog(null, "Número inválido. Ingrese un valor entre 1 y " + (valorInt * valorInt) + ".");
            inputMinas = JOptionPane.showInputDialog("Ingrese la cantidad de minas (1 - " + (valorInt * valorInt) + "):");

            if (inputMinas == null) {
                JOptionPane.showMessageDialog(null, "Operación cancelada. No se generará el tablero.");
                return;
            }

            cantidadMinas = helper.convertirNumero(inputMinas);
        }

// Generar las minas
        buscaMinaApp.setCantidadMinas(cantidadMinas);
        buscaMinaApp.generarMinas(cantidadMinas);

        Tablero v2 = new Tablero();
        this.dispose();
    }//GEN-LAST:event_continuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigTamaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigTamaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigTamaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigTamaño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigTamaño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuar;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner valorN;
    // End of variables declaration//GEN-END:variables
}
